#!/usr/bin/perl

use warnings;

use Cwd qw(abs_path);
use Getopt::Long;
use Pod::Usage;
Getopt::Long::Configure('bundling');

#
# Binary locations
#
our $CONVERT  = `which convert`;
our $IDENTIFY = `which identify`;
our $JHEAD    = `which jhead`;
chomp $CONVERT;
chomp $IDENTIFY;
chomp $JHEAD;

die "'convert' command not found\n" unless $CONVERT;
die "'identify' command not found\n" unless $IDENTIFY;
die "'jhead' command not found\n" unless $JHEAD;

#
# Image extensions
#
our $EXTENSIONS = join("|", qw( gif jpg jpeg png ));

#
# Command line options
#
our $INPUT_DIR;
our $OUTPUT_DIR;
our $ALBUM_TITLE;
our $MAX_WIDTH = 700;
our $MEDIUM_WIDTH  = 640;
our $MEDIUM_HEIGHT = 480;
our $PRINT_EXIF = 0;
our $SKIP_MEDIUMS = 0;
my $SKIP_THUMBS = 0;
my $SKIP_HTML = 0;
my $SKIP_METADATA = 0;
my $HELP;
GetOptions(
	'i=s' => \$INPUT_DIR,
	'o=s' => \$OUTPUT_DIR,
	'title|t=s' => \$ALBUM_TITLE,
    'width|w=i' => \$MAX_WIDTH,
    'h=i' => \$MEDIUM_HEIGHT,
    'w=i' => \$MEDIUM_WIDTH,
    'M|nomediums' => \$SKIP_MEDIUMS,
	'T|nothumbs' => \$SKIP_THUMBS,
	'H|nohtml' => \$SKIP_HTML,
	'D|nometa' => \&SKIP_METADATA,
    'e|exif' => \$PRINT_EXIF,
	'help|?' => \$HELP,
);
pod2usage(1) if ($HELP || !($INPUT_DIR && $OUTPUT_DIR));


#
# Check input directory
#
die "Input directory '$INPUT_DIR' doesn't exist.\n" if (!(-d $INPUT_DIR));

#
# Create directory variables
#
our $HTML_DIR   = 'html';
our $PHOTO_DIR  = 'photos';
our $MEDIUM_DIR = 'mediums';
our $THUMB_DIR  = 'thumbnails';
our $FULL_HTML_DIR   = "$OUTPUT_DIR/$HTML_DIR";
our $FULL_PHOTO_DIR  = "$OUTPUT_DIR/$PHOTO_DIR";
our $FULL_MEDIUM_DIR = "$OUTPUT_DIR/$MEDIUM_DIR";
our $FULL_THUMB_DIR  = "$OUTPUT_DIR/$THUMB_DIR";

# If title wasn't specified, default to the output directory name
my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time());
$year += 1900;
$mon++;
$mday = "0$mday" if $mday < 10;
$mon  = "0$mon"  if $mon < 10;
$ALBUM_TITLE = "albumize | $mon.$mday.$year" unless defined($ALBUM_TITLE);


#
# Execute the program
#
createOutputDirs();
createThumbnails() unless $SKIP_THUMBS;
createMediums() unless $SKIP_MEDIUMS;
createIndexHTML() unless $SKIP_HTML;
createPhotoHTML() unless $SKIP_HTML;
createMetadata() unless $SKIP_METADATA;

exit 0;

###############################################################################

#
# Create the output directories (if necesssary)
#
sub createOutputDirs {
    mkdir($OUTPUT_DIR);
    mkdir($FULL_HTML_DIR);
    mkdir($FULL_PHOTO_DIR);
    mkdir($FULL_MEDIUM_DIR) unless $SKIP_MEDIUMS;
    mkdir($FULL_THUMB_DIR);
}

#
# Create thumbnails
#
sub createThumbnails {
	print "generating thumbnails...\n";

	my @files = `ls -1 \"$INPUT_DIR\" | egrep -i \"$EXTENSIONS\"`;
	foreach $file (@files) {
		chomp $file;
		my $newFile = $file;
		$newFile =~ s/\s+/_/g;

		`cp \"$INPUT_DIR/$file\" $FULL_PHOTO_DIR/$newFile`;
		
		print "\t$FULL_THUMB_DIR/$newFile\n";
		`$CONVERT $FULL_PHOTO_DIR/$newFile -resize x120 +profile \"*\" $FULL_THUMB_DIR/$newFile`;
	}
}

sub createMediums {
    print "generating medium size images...\n";

	my @files = `ls -1 \"$FULL_PHOTO_DIR\"`;
	foreach $file (@files) {
		chomp $file;

		print "\t$FULL_MEDIUM_DIR/$file\n";

        my ($width, $height) = getImageSize("$FULL_PHOTO_DIR/$file");
        my $newSize;
        $newSize = $MEDIUM_WIDTH  .'x'. $MEDIUM_HEIGHT;
        #$newSize = $MEDIUM_HEIGHT .'x'. $MEDIUM_WIDTH if ($height > $width);

		# If the original image is larger than the medium height, resize it
		# Otherwise we don't need to do anything (since we don't want to -expand- pictures
		if ($height > $MEDIUM_HEIGHT) {
			`$CONVERT $FULL_PHOTO_DIR/$file -resize x$MEDIUM_HEIGHT +profile \"*\" $FULL_MEDIUM_DIR/$file`;
		} else {
			`cp $FULL_PHOTO_DIR/$file $FULL_MEDIUM_DIR/$file`;
		}
    }
}



sub createIndexHTML {
	print "generating index html...\n";
	open(INDEXHTML, ">$OUTPUT_DIR/index.html") or die "Cannot open $OUTPUT_DIR/index.html: $!\n";

	print INDEXHTML startHTML($ALBUM_TITLE);
	#print INDEXHTML "<h2>$ALBUM_TITLE</h2>\n";
	print INDEXHTML "<br>\n";
	
	my @thumbs = `ls -1 \"$FULL_THUMB_DIR\"`;
	my $pixels = 0;
	foreach $thumb (sort @thumbs) {
		chomp $thumb;

		my ($width, $height) = getImageSize("$FULL_THUMB_DIR/$thumb");
		$pixels += $width;
        print STDERR "\t pixels($pixels), w($width) h($height)\n";

		if ($pixels >= $MAX_WIDTH) {
			print INDEXHTML "<br>\n";
			$pixels = $width;
		}
			
		print INDEXHTML linkImage($thumb), "\n";
	}

	print INDEXHTML endHTML();

	close(INDEXHTML);
}

sub createPhotoHTML {
	print "generating photo html...\n";
	my @thumbs = `ls -1 \"$FULL_THUMB_DIR\"`;

	# Go through each thumbnail and create a webpage for it
	my $i;
	for ($i = 0; $i < @thumbs; $i++) {
		my $thumb = $thumbs[$i];
		chomp $thumb;

		my $imageName = getImageName($thumb);
		print "\t$FULL_HTML_DIR/$imageName.html\n";
		open(PHTML, ">$FULL_HTML_DIR/$imageName.html") or die "Cannot open $FULL_HTML_DIR/$imageName.html: $!\n";

		print PHTML startHTML($ALBUM_TITLE, $imageName);

		# Print navigation bar
		if ($i != 0) {
			print PHTML "<a href=\"", getImageName($thumbs[$i-1]), ".html\">previous</a>&nbsp;&nbsp;&nbsp;";
		} else {
			print PHTML "<font color=#888888>previous</font>&nbsp;&nbsp;&nbsp;";
		}
		print PHTML "<a href=\"../index.html\">up</a>";
		if ($i < $#thumbs) {
			print PHTML "&nbsp;&nbsp;&nbsp;<a href=\"", getImageName($thumbs[$i+1]), ".html\">next</a>";
		} else {
			print PHTML "&nbsp;&nbsp;&nbsp;<font color=#888888>next</font>";
		}

		#print PHTML "<p>\n";
		#print PHTML "<h2>$imageName</h2>\n";

		# Print photo
		print PHTML "<p>\n";
        if (-e "$FULL_MEDIUM_DIR/$thumb") {
            print PHTML "<a href=\"../$PHOTO_DIR/$thumb\"><img src=\"../$MEDIUM_DIR/$thumb\" border=1></a>\n";
            print PHTML "<p><font size=-2>Click image to enlarge</font>\n";
        } else {
            print PHTML "<img src=\"../$PHOTO_DIR/$thumb\" border=1>\n";
        }

        if ($PRINT_EXIF) {
            my $exif = getExifData("$FULL_PHOTO_DIR/$thumb");

            print PHTML "<hr width=360 align=left>\n";
			print PHTML "$exif\n";
        }

		print PHTML endHTML();

		close(PHTML);
	}
}

sub createMetadata {
	open(META, ">$OUTPUT_DIR/.metadata") or die "Cannot open $OUTPUT_DIR/.metadata: $!\n";
	print META "# albumize album\n\n";
	print META "timestamp=". time() . "\n";
	print META "title=$ALBUM_TITLE\n";
	print META "abs_input_dir=". abs_path($INPUT_DIR) ."\n";
	print META "rel_input_dir=$INPUT_DIR\n";
	print META "abs_output_dir=". abs_path($OUTPUT_DIR) ."\n";
	print META "rel_output_dir=$OUTPUT_DIR\n";
	print META "thumbnails_dir=$THUMB_DIR\n";
	print META "mediums_dir=$MEDIUM_DIR\n";
	print META "html_dir=$HTML_DIR/html\n";
	print META "photo_dir=$PHOTO_DIR\n";
	print META "indexpage=$OUTPUT_DIR/index.html\n";
	print META "exif=$PRINT_EXIF\n";
	print META "\n";

	# Print all the filenames we created
	foreach my $dir (($FULL_HTML_DIR, $FULL_PHOTO_DIR, $FULL_MEDIUM_DIR, $FULL_THUMB_DIR)) {
		foreach my $file (sort `ls -1 $dir`) {
			chomp $file;
			print META "created_file=$dir/$file\n";
		}
	}
	close(META);
}

#
# Utility methods
#
sub startHTML {
    my $title = shift;
	my $imageTitle = shift;
	my $string = <<EOF;
<html>
<head>
EOF

	if (defined($imageTitle)) {
		$string .= "<title>fourspace | photos | $title | $imageTitle</title>\n";
	} else {
		$string .= "<title>fourspace | photos | $title</title>\n";
	}
	
	$string .= <<EOF;
	<link rel="stylesheet" href="/content.css">
</head>

<body bgcolor=#D6D6D6
    text=#545454
    link=#444444
    alink=#444444
    vlink=#444444
    topmargin=0
    leftmargin=0
    marginheight=0
    marginwidth=0>
                                                                                
<table class="navbar">
<tr><td>
    <a href="/">fourspace</a> |
	<a href="/photos">photos</a> |
EOF
	if (defined($imageTitle)) {
		$string .= "<a href=\"../index.html\">$title</a> |\n";
		$string .= "$imageTitle\n";
	} else {
		$string .= "$title\n";
	}
	
	$string .= <<EOF;
</td></tr>
</table>

<div id="content">
EOF

	return $string;
}

sub endHTML {
	return "</div>\n</body>\n</html>\n";
}

sub getImageName($) {
	my $image = shift;
	my $imageName = $image;
	$imageName =~ s/\.[^.]+$//;

	return $imageName;
}

sub getImageSize($) {
	my $file = shift;
	
	my $imageData = `$IDENTIFY $file`;
	if ($imageData =~ /(\d+)x(\d+)/) {
		return ($1, $2);
	}

	return undef;
}

sub linkImage ($) {
	my $image = shift;
	my $imageName = getImageName($image);
	return "<a href=\"$HTML_DIR/$imageName.html\"><img src=\"$THUMB_DIR/$image\" border=1></a>";
}

sub getExifData($) {
	my $image = shift;
	my $data = "";
	open(JHEAD, "$JHEAD $image|") or die "Cannot open '$JHEAD $image': $!\n\n";
	while(<JHEAD>) {
		chomp;
		if (/^([^:]+)\s+:\s+(.*)\s*$/) {
			my ($key, $value) = ($1, $2);
			next if ($key =~ /File name/i);
			next if ($key =~ /File date/i);
			next if ($key =~ /Camera Make/i);

			# Format date/time
			if ($key =~ /Date\/Time/i) {
				my ($date, $time) = split(/\s+/, $value);
				my ($year, $month, $day) = split(/:/, $date);
				my ($hour, $min, $sec) = split(/:/, $time);
				my $timeOfDay = ($hour < 12) ? "am" : "pm";
				$hour -= 12 if ($hour > 12);
				$hour = 12 if ($hour eq "00");
				$hour = "0$hour" if ($hour < 10);
			
				$value = "$month/$day/$year, $hour:$min:$sec $timeOfDay EDT";
			}

			$data .= "$key: $value<br>";
		}
	}
	return $data;
}


__END__

=head1 NAME

albumize - Generate an HTML photo album for a set of images

=head1 SYNOPSIS

 albumize -i input_dir -o output_dir [OPTIONS]

 Options:
     --title,-t         Album title
     --width,-w         Maximum width (in pixels) for thumbnail rows
     -h <height>        Maximum height (in pixels) for medium size images
     -D, --nometa       Do not generate metadata file
     -H, --nohtml       Do not generate HTML
     -M, --nomediums    Do not generate medium size images
     -T, --nothumbs     Do not generate thumbnails
                        NOTE: Thumbnails must be in output_dir/thumbnails)
     -e, --exif         Print EXIF metadata for applicable JPEGs

=head1 AUTHORS

Tim Cheadle <F<session@fourspace.com>>
